#
# SurvivalBoom Discord Service | SurvivalBoom Network 2026
#            Logging Module | By Mycetik
#

database:
  # Скільки зберігати повідомлення та події в базі даних
  messages_ttl_hours: 336 # 2 тижні
  audit_ttl_hours: 336