#
#    ________  ____  ____   _______  ___      ___  __  ___      ___  __      ___       _______     ______      ______   ___      ___
#   /"       )("  _||_ " | /"      \|"  \    /"  ||" \|"  \    /"  |/""\    |"  |     |   _  "\   /    " \    /    " \ |"  \    /"  |
#  (:   \___/ |   (  ) : ||:        |\   \  //  / ||  |\   \  //  //    \   ||  |     (. |_)  :) // ____  \  // ____  \ \   \  //   |
#   \___  \   (:  |  | . )|_____/   ) \\  \/. ./  |:  | \\  \/. .//' /\  \  |:  |     |:     \/ /  /    ) :)/  /    ) :)/\\  \/.    |
#    __/  \\   \\ \__/ //  //      /   \.    //   |.  |  \.    ////  __'  \  \  |___  (|  _  \\(: (____/ //(: (____/ //|: \.        |
#   /" \   :)  /\\ __ //\ |:  __   \    \\   /    /\  |\  \\   //   /  \\  \( \_|:  \ |: |_)  :)\        /  \        / |.  \    /:  |
#  (_______/  (__________)|__|  \___)    \__/    (__\_|_)  \__/(___/    \___)\_______)(_______/  \"_____/    \"_____/  |___|\__/|___|
#
#                        SurvivalBoom Discord Service | By TIMURishche | SurvivalBoom Network 2026
#                                           Наш власний дискорд бот. Ми - найкращі!
#
#                                                     ! КОНФІГУРАЦІЯ !


#
# У цьому файлі знаходиться базова конфігурація ядра SBDS.
# Сам по собі SBDS нічого не робить, а тільки надає API для розробки модулів.
# Увесь функціонал SBDS реалізований за допомогою модулів - окремих .jar файлів із кодом.
#
# Налаштування кожного з модулів знаходиться у modules/назва-модуля/config.yml (якщо модуль взагалі має якісь налаштування)
# У більшості випадків, модулі зберігають конфігурацію персонально для кожного користувача або сервера у базі даних SBDS.
# Це зроблено для того, щоб SBDS можна було використовувати на різних серверах одночасно.
#

# База даних SBDS.
# Саме у базі даних зберігаються усі дані про користувачів,
# а також налаштування інших діскорд серверів якщо ви дозволите це.
#
# SBDS використовує Hibernate для роботи із базою даних.
#
database:

  # JDBC конфігурація. Якщо ви не знаєте як із цим працювати, можете викинутись з вікна.
  # Теоретично, ви можете вписати сюди будь-який тип бази даних.
  # SBDS використовує Hibernate для збереження даних, тому це будуть вже його проблеми як із цим працювати.
  # Але, все ж таки не забувайте про драйвер JDBC, що має бути в jar файлі SBDS.
  #
  # Взагалі, якщо ви відчайдух, можете впихнути в .jar файл необхідний вам драйвер самотужки.
  # За замовчуванням SBDS поставляється із драйверами для PostgreSQL, MySQL та SQLite.
  #
  # Рекомендуємо використовувати PostgreSQL, оскільки SBDS зберігає більшість даних у JSON.
  # PostgreSQL має вбудовану підтримку JSON й зберігає його не просто як звичайний текст.
  #
  # Приклади:
  # > PostgreSQL => jdbc:postgresql://yourdomain.com/database
  # > MySQL => jdbc:mysql://yourdomain.com/database
  # > SQLite => jdbc:sqlite:./data/database.db
  #
  # Плейсхолдери:
  # - {SBDS-DIR} - Директорія у якій знаходиться бот.
  #
  jdbc: "jdbc:sqlite:{SBDS-DIR}/data/database.db"

  # Драйвер (class файл в .jar SBDS) що буде використовуватись для з'єднання.
  # Має відповідати протоколу JDBC, що ви вказали вище.
  # Ось кілька прикладів:
  # > PostgreSQL => org.postgresql.Driver
  # > MySQL 8+ => com.mysql.cj.jdbc.Driver
  # > SQLite => org.sqlite.JDBC
  driver: "org.sqlite.JDBC"

  # Діалект що буде використовуватись Hibernate при генерації SQL запитів до бази даних.
  # Ось кілька прикладів:
  # > PostgreSQL => org.hibernate.dialect.PostgreSQLDialect
  # > MySQL 8+ => org.hibernate.dialect.MySQL8Dialect
  # > SQLite => org.sqlite.hibernate.dialect.SQLiteDialect
  dialect: "org.hibernate.community.dialect.SQLiteDialect"

  # ! Важливо !
  # Цей параметр відповідає за взаємодію Hibernate із таблицями!
  # При перевірці структури таблиць Hibernate:
  # * create - кожен раз створює нові таблиці, видаляючи старі (Знищення даних!)
  # * create-drop - те саме що й 'create', але видаляє таблиці при завершенні роботи програми.
  # * update - оновлює структуру таблиць якщо вона не відповідає коду. Дані не знищуються, додаються нові колонки якщо треба. Але все одно, іноді небезпечно. Добре підходить для тестування.
  # * validate - перевіряє структуру таблиць, але не чіпає їх якщо вони не відповідають коду. Підходить якщо ви боїтесь втратити дані.
  # * none - не перевіряє нічого й не чіпає нічого (може привести до неправильної роботи!)
  mode: update

  # user: dinoZavrik # Користувач.
  # password: abobus2024 # Пароль.

  # Hibernate має конфігураційний файл, що зазвичай розміщується всередині jar.
  # Але SBDS конфігурує Hibernate програмно. У цій секції ви можете встановити будь-які параметри Hibernate.
  # Не встановлюйте тут driver, jdbc та дані для входу у базу даних. Вони будуть перезаписані параметрами вище.
  properties:

    hibernate.show_sql: false # Показувати SQL запити від Hibernate у консолі? (Для тестування)
    hibernate.format_sql: false # Форматувати SQL запити для покращеної читабельності?

    # Налаштування Hikari для підключення.
    # Якщо не знаєте що це, не чіпайте.
    hikari.minimumIdle: 5
    hikari.maximumPoolSize: 20
    hikari.idleTimeout: 30000
    hikari.maxLifetime: 1800000
    hikari.connectionTimeout: 30000

# Налаштування логування.
logging:

  # Рівень глобального логування у консолі.
  # Може бути: DEBUG INFO WARN ERROR
  global-level: INFO

  # Правила показу логів у консолі від конкретних логерів.
  rules:

    # Правило для Hibernate аби він не срав у консоль своєю нахуй не потрібною хуйнею.
    hibernate:
      pattern: org.hibernate
      level: WARN

    hikari:
      pattern: com.zaxxer.hikari
      level: WARN

    jda:
      pattern: net.dv8tion.jda
      level: WARN

# Налаштування Discord бота.
bot:

  # Які gateway intents запитувати у Discord при запуску SBDS.
  # Значення має відповідати переліку з https://jda.wiki/using-jda/gateway-intents/
  # Привілейовані інтенти (GUILD_MEMBERS, GUILD_PRESENCES, MESSAGE_CONTENT) потребують увімкнення у Discord Developer Portal.
  # Лишіть список пустим, щоб SBDS використовував усі можливі Gateway Intents.
  # Або ж вкажіть конкретні Gateway Intents, якщо у вас якийсь специфічний випадок використання.
  gateway-intents: []

#
# SBDS підтримує систему перекладів.
# За замовчуванням, користувач може обрати переклад що буде використовуватись у повідомленнях від бота користувачу.
# Також адміністратори діскорд серверів на яких знаходиться бот, можуть встановити мову для їх сервера за замовчуванням.
#
# Тут ви можете налаштувати деякі глобальні параметри перекладів.
translations:

  # Переклад який буде використовуватись за замовчуванням
  # у випадку якщо користувач не встановив переклад для себе.
  default: sbds:english

  # Резервний переклад. Використовується у випадках коли повідомлення не знайдено у перекладі користувача.
  # Якщо повідомлення не буде знайдено навіть у цьому перекладі,
  # замість необхідного повідомлення буде просто плейсхолдер `$[path.to.message]`.
  fallback: sbds:ukrainian

  # Чи надсилати у консоль попередження про повідомлення яке було не знайдно у перекладі?
  # true - Кожен раз коли SBDS не знайде повідомлення з перекладу, у консоль буде надіслано попередження.
  # false - SBDS буде просто ігнорувати подібні ситуації.
  warn-missing: true

#
# SBDS має власну систему груп і дозволів (схоже на LuckPerms)
# Зазвичай кожен модуль сам налаштовує стандартні дозволи для кожної групи.
# Але ви можете вручну задати необхідні вам групи та дозволи вручну.
#
# Запис дозволів відбувається всередині секції групи.
# Формат запису дозволу `дозвіл:значення`. Приклад: `sbds.command.test:true`.
#
global-permissions:

  # Група default - стандартна група яку мають усі користувачі за замовчуванням.
  # Має пріоритет 0.
  default:
    permissions:
      - "testmodule.command.testcommand:true"

#
# Бібліотеки на яких працює SBDS.
# Не видаляйте стандартні бібліотеки SBDS, інакше він просто не запуститься.
#
# Якщо вам потрібна якась бібліотека, можете дописати цю секцію.
# Але зазвичай, бібліотеки мають бути вказані у секції `libraries` в module.yml для кожного модуля.
# При запуску SBDS перевіряє та завантажує усе бібліотеки.
#
# SBDS завантажує деякі драйвери для підключення до баз даних.
# Ви можете додати необхідні вам чи прибрати зайві.
#
libraries:

  pinned:
    - "org.slf4j:slf4j-api:2.0.16"

  dependencies:
    - "org.spongepowered:configurate-jackson:4.2.0" # Підтримка JSON для Configurate за допомогою Jackson.
    - "net.dv8tion:JDA:6.4.1" # JDA - фреймворк для розробки discord ботів на java
    - "org.hibernate.orm:hibernate-core:6.6.9.Final" # Hibernate - фреймворк для роботи із базою даних.
    - "com.zaxxer:HikariCP:6.2.1" # HikariCP - дуже ефективний pool з'єднань із базою даних.
    - "org.hibernate.orm:hibernate-hikaricp:6.6.9.Final" # Підтримка HikariCP для Hibernate.
    - "org.hibernate.orm:hibernate-community-dialects:6.6.9.Final" # Діаклекти Hibernate для підтримки різних типів баз даних, наприклад SQLite.
    - "org.postgresql:postgresql:42.7.5" # Драйвер JDBC для підключення до PostgreSQL.
    - "com.mysql:mysql-connector-j:9.2.0" # Драйвер JDBC для підключення до MySQL
    - "org.xerial:sqlite-jdbc:3.49.1.0" # Драйвер JDBC для підключення до SQLite.